# Generated by Django 6.0.7 on 2026-08-24 22:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iande", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCache",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A unique identifier for this conversation",
                        unique=True,
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        db_index=True,
                        help_text="The tag for the value",
                        max_length=256,
                        unique=True,
                    ),
                ),
                (
                    "markdown",
                    models.TextField(help_text="Markdown of the website cache"),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags associated with this cache",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
