# Generated by Django 6.0.7 on 2026-08-25 15:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iande", "0002_blogcache"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceClone",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A unique identifier for this voice clone",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this voice", max_length=128
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Reference audio clip used for voice cloning",
                        upload_to="iande/voices",
                    ),
                ),
                (
                    "exaggeration",
                    models.FloatField(
                        default=2.4, help_text="Chatterbox exaggeration parameter"
                    ),
                ),
                (
                    "cfg_weight",
                    models.FloatField(
                        default=1.5, help_text="Chatterbox cfg weight parameter"
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
