# Generated by Django 6.0.7 on 2026-08-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iande', '0003_voiceclone'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceclone',
            name='voice_model',
            field=models.CharField(default='xxx', help_text='Snake case model name', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
